import { Community, CommunityCategory } from './types';

export const COMMUNITIES: Community[] = [
  // --- Community (General/Tech/Humor) ---
  {
    id: 'dcinside',
    name: '디시인사이드',
    emoji: '⚾',
    url: 'https://gall.dcinside.com/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Cynical, informal "Banmal", short. Treat the link as "Source" or "Verification". Don\'t beg for clicks. Use slang like "~했노", "~다".',
    color: 'bg-blue-900',
  },
  {
    id: 'fmkorea',
    name: 'FM코리아',
    emoji: '⚽',
    url: 'https://www.fmkorea.com/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Informal, logical, factual. "Here is the fact check: [Link]". Mix humor with facts. Standard internet slang.',
    color: 'bg-blue-600',
  },
  {
    id: 'clien',
    name: '클리앙',
    emoji: '📱',
    url: 'https://www.clien.net/service/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Polite "Honorifics" (Jon-dae-mal). "I found some good info and organized it here." Intellectual and tech-savvy tone.',
    color: 'bg-slate-700',
  },
  {
    id: 'theqoo',
    name: '더쿠',
    emoji: '🎵',
    url: 'https://theqoo.net/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Excited, fan-girl tone. "Omg look at this [Link]". Use exclamation marks and friendly informal speech.',
    color: 'bg-yellow-600',
  },
  {
    id: 'natepann',
    name: '네이트판',
    emoji: '🔥',
    url: 'https://pann.nate.com/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Emotional, storytelling style. "I\'m writing this with trembling hands...", "Real life review". Focus on empathy or shock. Use "Eum-sme-che" or polite style.',
    color: 'bg-red-600',
  },
  {
    id: 'mlbpark',
    name: 'MLB파크',
    emoji: '⚾',
    url: 'https://www.mlbpark.com/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Polite but opinionated (~yo ending). Male 30s-40s tone. "I analyzed this seriously". Logical but stubborn.',
    color: 'bg-orange-700',
  },
  {
    id: 'ou',
    name: '오늘의 유머',
    emoji: '😂',
    url: 'http://www.todayhumor.co.kr/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Polite, slightly old-school. "Sharing some warm news/info." Use honorifics.',
    color: 'bg-orange-500',
  },
  {
    id: 'instiz',
    name: '인스티즈',
    emoji: '💫',
    url: 'https://www.instiz.net/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Soft, female-dominant tone. "Heol daebak, have you seen this? [Link]". Use cute endings.',
    color: 'bg-pink-400',
  },
  {
    id: 'everytime',
    name: '에브리타임',
    emoji: '🏫',
    url: 'https://everytime.kr/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'University student tone. Short, relatable, slang. "Exam period vibes". Campus life focus.',
    color: 'bg-red-500',
  },
  {
    id: 'ddanzi',
    name: '딴지일보',
    emoji: '📰',
    url: 'https://www.ddanzi.com/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Sarcastic, political, critical. "Read the truth here: [Link]". Old-school resistance vibe.',
    color: 'bg-red-800',
  },
  {
    id: 'reddit',
    name: '레딧 (해외)',
    emoji: '👽',
    url: 'https://www.reddit.com/',
    category: CommunityCategory.COMMUNITY,
    tonePrompt: 'Witty, informative title. "TL;DR in comments but full story here: [Link]". Global internet vibe.',
    color: 'bg-orange-600',
  },
  
  // --- Shopping ---
  {
    id: 'ppomppu',
    name: '뽐뿌',
    emoji: '💸',
    url: 'https://www.ppomppu.co.kr/',
    category: CommunityCategory.SHOPPING,
    tonePrompt: 'Price-focused. "Hot deal alert! [Link]". Critical about cost-effectiveness.',
    color: 'bg-gray-600',
  },
  
  // --- Gaming ---
  {
    id: 'ruliweb',
    name: '루리웹',
    emoji: '🎮',
    url: 'https://bbs.ruliweb.com/',
    category: CommunityCategory.GAME,
    tonePrompt: 'Otaku/Gamer friendly. "New info released: [Link]". Informal but respectful.',
    color: 'bg-blue-500',
  },
  {
    id: 'inven',
    name: '인벤',
    emoji: '👾',
    url: 'https://www.inven.co.kr/',
    category: CommunityCategory.GAME,
    tonePrompt: 'Hardcore analytical. "Stats analysis here: [Link]". Critical tone.',
    color: 'bg-zinc-800',
  },
  {
    id: 'hungryapp',
    name: '헝그리앱',
    emoji: '📱',
    url: 'http://www.hungryapp.co.kr/',
    category: CommunityCategory.GAME,
    tonePrompt: 'Casual mobile gamer. "Coupon code/Event info: [Link]".',
    color: 'bg-red-500',
  },

  // --- Special Interest ---
  {
    id: '82cook',
    name: '82쿡',
    emoji: '🍳',
    url: 'https://www.82cook.com/',
    category: CommunityCategory.SPECIAL,
    tonePrompt: 'Housewife tone, polite. "I tried this recipe/tip and it was great. Details: [Link]".',
    color: 'bg-orange-400',
  },
  {
    id: 'bobaedream',
    name: '보배드림',
    emoji: '🚘',
    url: 'https://www.bobaedream.co.kr/',
    category: CommunityCategory.SPECIAL,
    tonePrompt: 'Masculine, justice-seeking. "Black box footage/Full story: [Link]". Rough but loyal.',
    color: 'bg-blue-800',
  },
  {
    id: 'slrclub',
    name: 'SLR클럽',
    emoji: '📷',
    url: 'http://www.slrclub.com/',
    category: CommunityCategory.SPECIAL,
    tonePrompt: 'Middle-aged male tone. "Sample shots here: [Link]". Technical and polite.',
    color: 'bg-blue-400',
  },
  {
    id: 'coolenjoy',
    name: '쿨엔조이',
    emoji: '🖥️',
    url: 'https://coolenjoy.net/',
    category: CommunityCategory.SPECIAL,
    tonePrompt: 'PC hardware enthusiast. "Benchmark results: [Link]". Polite and technical.',
    color: 'bg-orange-600',
  },
  {
    id: 'quasarzone',
    name: '퀘이사존',
    emoji: '👽',
    url: 'https://quasarzone.com/',
    category: CommunityCategory.SPECIAL,
    tonePrompt: 'High-end tech. "Unboxing/Review: [Link]". Very polite enthusiast.',
    color: 'bg-orange-700',
  },
  {
    id: '2cpu',
    name: '2CPU',
    emoji: '💻',
    url: 'https://www.2cpu.co.kr/',
    category: CommunityCategory.SPECIAL,
    tonePrompt: 'Server/IT expert. "Technical documentation/Source: [Link]". Professional.',
    color: 'bg-slate-600',
  },
  {
    id: 'mule',
    name: '뮬 (악기/음악)',
    emoji: '🎸',
    url: 'https://www.mule.co.kr/',
    category: CommunityCategory.SPECIAL,
    tonePrompt: 'Musician tone. "Sound sample/Gear review: [Link]". Professional but community-focused.',
    color: 'bg-emerald-700',
  },

  // --- Social Media ---
  {
    id: 'threads',
    name: '스레드 (Threads)',
    emoji: '🧵',
    url: 'https://www.threads.net/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Casual, conversational, Twitter-like but cleaner. "Just leaving this here...", "Current mood:". Minimalist. Thread format.',
    color: 'bg-black',
  },
  {
    id: 'instagram',
    name: '인스타그램',
    emoji: '📸',
    url: 'https://www.instagram.com/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Aesthetic, emotional. "Check link in bio for more!". Lots of emojis and hashtags.',
    color: 'bg-pink-600',
  },
  {
    id: 'twitter',
    name: 'X (트위터)',
    emoji: '🐦',
    url: 'https://twitter.com/compose/tweet',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Short, witty. "Thread 👇", "Full story: [Link]". Cynical or funny.',
    color: 'bg-black',
  },
  {
    id: 'facebook',
    name: '페이스북',
    emoji: '👍',
    url: 'https://www.facebook.com/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Informative card-news style. "Click to read more". Standard tone.',
    color: 'bg-blue-700',
  },
  {
    id: 'band',
    name: '네이버 밴드',
    emoji: '👥',
    url: 'https://band.us/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Friendly notice. "Please check the announcement here: [Link]".',
    color: 'bg-green-600',
  },
  {
    id: 'linkedin',
    name: '링크드인',
    emoji: '👔',
    url: 'https://www.linkedin.com/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Professional insight. "Read my full article here: [Link]". Business oriented.',
    color: 'bg-blue-700',
  },
  {
    id: 'blind',
    name: '블라인드',
    emoji: '🏢',
    url: 'https://www.teamblind.com/kr/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Professional, cynical, realistic. "Honest industry review". Employee perspective. Anonymous vibe.',
    color: 'bg-slate-800',
  },
  {
    id: 'tiktok',
    name: '틱톡',
    emoji: '🎵',
    url: 'https://www.tiktok.com/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Short caption. "Link in bio for tutorial!". Trendy slang.',
    color: 'bg-black',
  },
  {
    id: 'pinterest',
    name: '핀터레스트',
    emoji: '📌',
    url: 'https://www.pinterest.co.kr/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Inspirational. "Visit site". Visual focus.',
    color: 'bg-red-600',
  },
  {
    id: 'telegram',
    name: '텔레그램',
    emoji: '✉️',
    url: 'https://telegram.org/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Direct and urgent. "New update/Alpha: [Link]". Minimalist.',
    color: 'bg-sky-500',
  },
  {
    id: 'twitch',
    name: '트위치',
    emoji: '📺',
    url: 'https://www.twitch.tv/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Streamer vibe. "Live now! Come hang out: [Link]". Energetic.',
    color: 'bg-purple-600',
  },
  {
    id: 'afreecatv',
    name: '아프리카TV',
    emoji: '🎬',
    url: 'https://www.afreecatv.com/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Broadcasting vibe. "Go to live station: [Link]".',
    color: 'bg-blue-500',
  },
  {
    id: 'chzzk',
    name: '치지직 (네이버)',
    emoji: '⚡',
    url: 'https://chzzk.naver.com/',
    category: CommunityCategory.SOCIAL,
    tonePrompt: 'Game streamer vibe. "Streaming on Chzzk now: [Link]".',
    color: 'bg-green-500',
  },

  // --- Blog / Media ---
  {
    id: 'naverblog',
    name: '네이버 블로그',
    emoji: '✍️',
    url: 'https://blog.naver.com/',
    category: CommunityCategory.BLOG,
    tonePrompt: 'Detailed review teaser. "I wrote a detailed post about X. Read here: [Link]". Friendly.',
    color: 'bg-green-500',
  },
  {
    id: 'tistory',
    name: '티스토리',
    emoji: '📝',
    url: 'https://www.tistory.com/',
    category: CommunityCategory.BLOG,
    tonePrompt: 'Information sharing. "Source code/Full text: [Link]". Clean and professional.',
    color: 'bg-orange-500',
  },
  {
    id: 'navercafe',
    name: '네이버 카페',
    emoji: '☕',
    url: 'https://section.cafe.naver.com/',
    category: CommunityCategory.BLOG,
    tonePrompt: 'Community sharing. "I organized the info for members: [Link]". Polite.',
    color: 'bg-green-600',
  },
  {
    id: 'knowledgein',
    name: '네이버 지식인',
    emoji: '❓',
    url: 'https://kin.naver.com/',
    category: CommunityCategory.BLOG,
    tonePrompt: 'Expert answer. "You can find more details in my blog post: [Link]". Helpful.',
    color: 'bg-green-400',
  },
  {
    id: 'quora',
    name: '쿼라 (Quora)',
    emoji: '💡',
    url: 'https://ko.quora.com/',
    category: CommunityCategory.BLOG,
    tonePrompt: 'Intellectual deep dive. "I expanded on this topic here: [Link]".',
    color: 'bg-red-700',
  },
];